[phases.setup]
nixPkgs = [
  "ffmpeg",
  "python311",
  "cairo",
  "gobject-introspection",
  "pkg-config",
  "chromium",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "libdrm",
  "libxkbcommon",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXfixes",
  "xorg.libXrandr",
  "mesa",
  "expat",
  "xorg.libxcb"
]

[phases.install]
cmds = [
    "python3.11 -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt",
    ". /opt/venv/bin/activate && playwright install chromium --with-deps",
    ". /opt/venv/bin/activate && npm install -g hyperframes"
]

[start]
cmd = "python3.11 main.py run"